[package]
name = "themisto_remapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = { version = "4.0.26", features = ["derive"] }
clap_complete = "4.0.6"
tempfile = "3.8.1"
